### ISSUE TITLE
SyntaxError at "add_rev"

### ISSUE THREAD

**Issue by bioermaf** [Lattice-Automation/primers#1]
![企业微信截图_15876077347760](https://user-images.githubusercontent.com/64178494/80051356-94475b80-854a-11ea-9667-be4923a86f86.png)

**Comment by jjti** [comment]
Thanks for pointing this out. I just changed it in the README to the following: 

```python
fwd, rev = primers("AATGAGACAATAGCACACACAGCTAGGTCAGCATACGAAA", add_fwd="GGTCTC", add_rev="GAAGAC")
```
